name: TEst react App
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Get tho repo code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Test application
        run: npm run test